# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9a3dc361510e9cd8f6265774fcdad183dcabf0307e7547ee78346f5ae12bd379bc7b126709f0a2d086022d87120f07195f5b763a36cd2c5f94cd9210398b028

test:
  secret_key_base: 9b69d0e6c8f088cb8bbc69bfd5ff6c7da080411fab38a4fa63cd80988765192c9247ca145f159981955b4cdd63c5a4c4379e36c708c4ae90833df7007a0a3f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
